name: release

on:
  push:
    branches: master

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    env:
      ROOT: Assets/AsepriteImporter
    steps:
      - uses: actions/checkout@v2
      - name: get package
        id: package
        run: |
          echo "data=$(cat ${{ env.ROOT }}/package.json | tr -d '\n')" >> $GITHUB_OUTPUT

      - name: get git commit
        id: commit
        run: |
          echo "data=$(git log --pretty='%h %s' -1)" >> $GITHUB_OUTPUT

      - name: prepare release
        run: |
          git subtree split -P "${{ env.ROOT }}" -b "${{ env.BRANCH }}"
          git checkout "${{ env.BRANCH }}"
          git mv Samples Samples~
          rm -f Samples.meta
          # git push -f origin "${{ env.BRANCH }}"
        env:
          BRANCH: release-tmp

      - name: add branch
        run: |
          git fetch
          git reset --soft origin/release
          git checkout release
          git config --global user.name 'github-bot'
          git config --global user.email 'github-bot@users.noreply.github.com'
          git commit -am "release-${{ fromJson(steps.package.outputs.data).version }}" -m "${{ steps.commit.outputs.data }}"
          git status
          git push origin release

      - name: add tag
        run: |
          git tag -f ${{ env.TAG }}
          git push -f origin ${{ env.TAG }}
        env:
          TAG: release-${{ fromJson(steps.package.outputs.data).version }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ fromJson(steps.package.outputs.data).version }}
          release_name: v${{ fromJson(steps.package.outputs.data).version }}
          body: https://github.com/negi0109/unity-aseprite-importer.git#release-${{ fromJson(steps.package.outputs.data).version }}
          draft: false
          prerelease: false
